# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - lorry-dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://lorrydev.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_35603996d7574fc49156d01cfbb395b1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0299c3d6d0db438cbaf80f3ea8a17481 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: lorrydev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_35603996d7574fc49156d01cfbb395b1 }}/lorry:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lorry-dev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6878bdbec65443f6a7b780b23f942e1e }}
        images: 'lorrydev.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_35603996d7574fc49156d01cfbb395b1 }}/lorry:${{ github.sha }}'